### ISSUE TITLE
Profile graph: GUI changes

### ISSUE THREAD

**Issue by 40copoka** [SpaeroGIS/DPP#68]
- The Graph window should have the table with the Profile properties apart from the Graph like on the following picture
- there should be a "point of view" field as a Graph property. On changing the value in the filed, it should change the "visibility" paths on the profiles 
- On select a profile on the Graph, ti should  select the  row in the profile properties table
- There should be ability to reflect (means flesh) on the Active Map the point which was taken (by  a mouse click) from a profile line.
- If the number of profiles more then 1 the lines in the Graph should be in different color. It would be good to mark a row in the Profile Properties table with the color of the related line on the Graph
- the title of a Tab should have a Profile session name as the Tab title 
- The max and min values of the Height axis should have at least 10 % of the absolute height of the profile. If a session has more then one profile, then max and min are chosen between all points
absHeight = (max-min); max = max + (absHeight * 10%); min = min - (absHeight * 10%)

![image](https://user-images.githubusercontent.com/11270420/55485024-47889e00-5632-11e9-86b5-7116877734b7.png)

**Comment by 40copoka** [comment]
- The tab header should be combined as the word "Graph" + the sequence number of the tab like "Graph 1".
- the field "Height of point of view" should be under the table? in the Profile details ares

**Comment by DemonScarlett** [comment]
![image](https://user-images.githubusercontent.com/28986885/56422276-3c2ea700-62af-11e9-9664-0c86e7444191.png)

**Comment by 40copoka** [comment]
Graph toolbar:
![image](https://user-images.githubusercontent.com/11270420/56423878-a7c84280-62b6-11e9-9bcc-002b209ec7f4.png)
•	  What does this button mean? (not described in doc) 
•	   Does external buttons supposed to paging through tabs and internal scrolling graph?
•	  Can I choose a profile without clicking this button and if I can, then why is it needed?
•	   What kind of comments do we have to display?
•	  Update means resetting heights and colors to defaults?
•	  Show all profiles means resetting zoom?
•	  Does this button add new tab with profiles or empty?
•	  Should I delete button report? 
•	  Where and in which format we save image?
Properties tool bar:
•	What does it mean to refresh table if its values update with profile changing?
•	“Data export” – where? Only profile data without properties or not?
•	“Change profile view” – what does it mean?

**Comment by 40copoka** [comment]
Changes for the Graph view
![image](https://user-images.githubusercontent.com/11270420/56430341-c3d7de00-62ce-11e9-89b4-5bcdf380830d.png)

- Fit the Graph area to the center of view
- Make the number marks smaller. Fit them to the Tab title font
- Make the rows height smaller and fit the font to the Tab title font
- Add the check box to show\hide a line on the Graph
- Apply the value of the "Point of view" field to the selected row after leaving the field
- The button "Change height of the point of view" should change the value for all records
- The value of First point and the Last should contain the Geographic coordinates instead of length and height
- Make the areas for changing color shorter and higher
